# SQL

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: RubyCallLogger
  pool: 5
  username: sa
  password: mcmc2014!
  host: 192.168.63.36\SQLSERVER2008R2
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: RubyCallLogger
  pool: 5
  username: sa
  password: mcmc2014!
  host: 192.168.63.36\SQLSERVER2008R2

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: RubyCallLogger
  pool: 5
  username: sa
  password: mcmc2014!
  host: 192.168.63.36\SQLSERVER2008R2
  